name: CI/CD Pipeline

on:
  push:
    branches:
      - Wins
  pull_request:
    branches:
      - Wins

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or the version of Node.js you're using

      - name: Install dependencies
        run: |
          cd src  # Change directory to the src folder where your frontend code is
          npm install

      - name: Build frontend
        run: |
          cd src  # Change directory to the src folder where your frontend code is
          npm run build

      - name: Run tests
        run: |
          cd src  # Change directory to the src folder where your frontend code is
          npm test -- --watchAll=false # Run tests without watch mode
