name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Wins

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust the Node.js version if needed

      - name: Install dependencies
        run: |
          cd src # Navigate to your frontend directory
          npm install

      - name: Build
        run: |
          cd src # Navigate to your frontend directory
          npm run build

      - name: Run tests
        run: |
          cd src # Navigate to your frontend directory
          npm test -- --watchAll=false
